apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
  namespace: yarp-proxy
  labels:
    app: yarp-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yarp-proxy
  template:
    metadata:
      labels:
        app: yarp-proxy
    spec:
      containers:
        - name: yarp-proxy
          image: aksingressacr.azurecr.io/yarp-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: yarp-config